### ISSUE TITLE
Export to PNG on OSX

### ISSUE THREAD

**Issue by eadz** [stepan-mitkin/drakon_editor#2]
Hi,

First off, thanks for DRAKON. It is very impressive!

Just wanted to say that with a large graph, export to PNG on OSX doesn't seem to work properly. I end up with a mangled image.

**Comment by vasili111** [comment]
Added warning for a user before exporting to PNG: "Please, do not move or open any window or diagram while exporting to PNG."

Added English and Russian version of warning.

https://github.com/stepan-mitkin/drakon_editor/commit/4e461dfb90fa1346db742ae06a0a6eb287423c3f
