### ISSUE TITLE
Help appreciated: drakon on Macbook Air M1 (Apple Silicon)

### ISSUE THREAD

**Issue by mro** [stepan-mitkin/drakon_editor#48]
anybody got it running? https://platform.activestate.com/mro2020/ActiveTcl-8.6  SEGFAULTs and the recipe from https://github.com/stepan-mitkin/drakon_editor/issues/18#issuecomment-329899915 fails with

```
$ git clone https://github.com/waddella/tkimg.git
$ TCLLIBPATH=tkimg/inst/Img-Darwin64 tclsh8.6 drakon_editor.tcl
dlopen(tkimg/inst/Img-Darwin64/libtkimgwindow1.4.6.dylib, 6): no suitable image found.  Did find:
	tkimg/inst/Img-Darwin64/libtkimgwindow1.4.6.dylib: mach-o, but wrong architecture
	tkimg/inst/Img-Darwin64/libtkimgwindow1.4.6.dylib: stat() failed with errno=25
This script requires Img package.
Consider installing libtk-img.
```

any idea?

**Comment by mro** [comment]
really nobody?

**Comment by mro** [comment]
Hi @waddella, can you give me a hint how to get it running on a arm64 M1?

**Comment by mro** [comment]
Hi @waddella, sorry for bugging you, could you lend me a hand how to get drakon up? You managed it, wight?

**Comment by techieshark** [comment]
I had to compile from source. 


```
brew install tcl-tk

cd ~ # below we install in the home directory but you can modify as needed, just update --prefix and TCLLIBPATH further below too

svn checkout https://svn.code.sf.net/p/tkimg/code/trunk tkimg-code

cd tkimg-code

./configure \
  --with-tcl=/opt/homebrew/Cellar/tcl-tk/8.6.13_2/lib  \
  --with-tk=/opt/homebrew/Cellar/tcl-tk/8.6.13_2/lib \
  --prefix=/Users/<YOUR-USERNAME>/tk-img

make

make install
```

Then to run the script

```
TCLLIBPATH=/Users/<YOUR-USERNAME>/tkimg-code/Img /opt/homebrew/Cellar/tcl-tk/8.6.13_2/bin/tclsh8.6 ./drakon_editor.tcl
```

Note, replace `<YOUR-USERNAME>` above with your user (shown by `whoami` command).

(This gets Drakon to start, but I then run into some as-of-yet unsolved issue with "bad-db" - https://github.com/stepan-mitkin/drakon_editor/issues/51)
