### ISSUE TITLE
Golang as an output language

### ISSUE THREAD

**Issue by joeblew99** [stepan-mitkin/drakon_editor#8]
I would like golang to be added.
Golang is a very simple language and so it might not be too hard to support it.

What do others feel about this ?

**Comment by stepan-mitkin** [comment]
Go language support has been added added.

**Comment by joeblew99** [comment]
Wow. Gotta try it

**Comment by joeblew99** [comment]
I don't see it  in the generators

**Comment by stepan-mitkin** [comment]
The code generator should be there. Have you downloaded the official realease?
http://sourceforge.net/projects/drakon-editor/files/drakon_editor1.27.zip/download

Here is the generator in the source code:
https://github.com/stepan-mitkin/drakon_editor/blob/master/generators/go.tcl

**Comment by joeblew99** [comment]
Sorry did not see it when I last looked. Thanks, I will have a play.

One of the things I would like to try is to generate the draken description
from the go code. I can see how impossible this , but the only saving grace
if to maybe mark the go code with declarative attributes that are used to
represent drakon types.

I expect this is against the whole ethos of drakon but in the go world
there is allot of code gen of service layers and so it might be a way of
generating code that uses different transport. For example rest,
websickets, RPC, protocol buffers, channels, etc

Any thoughts. ??
